"""Atributo budget_limit

Revision ID: ae0c80701111
Revises: e44b1d747461
Create Date: 2025-02-23 16:37:54.775137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae0c80701111'
down_revision: Union[str, None] = 'e44b1d747461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('budget_limit', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'budget_limit')
    # ### end Alembic commands ###
